### ISSUE TITLE
Incorrect sctructure in .conf files

### ISSUE THREAD

**Issue by toniosj** [BenoitBounar/Pack-Conf-eXoDOS6.0r2-for-DosBOX-Pure-RECALBOX#2]
Example:
Aliens (1996)(Christoph Roschter).conf
.............
```
[autoexec]
cd aliens96
c:
call run
```

Why "c:" after "cd aliens96"? 
______________________________________________
MegaRace 2 (1996).conf
................
```
[autoexec]
cd MegaRac2
imgmount -u d
imgmount d ".\cd\megar1.iso" ".\cd\megar2.iso" -t cdrom
c:
cd MEGA2
echo.
echo This game has 2 CD's.  Press ctrl-F4 when prompted to switch discs.
echo.
pause
MEGARACE
```

Same problem, "c:" after "cd MegaRac2" ?

Question: Are you using original eXodos .zip files?

**Comment by BenoitBounar** [comment]
Thanks I will fix that.
Yes the pack works for and only for the eXoDOS Original pack

**Comment by BenoitBounar** [comment]
ISO 8:3 convertion done !
