### ISSUE TITLE
Missing .conf files

### ISSUE THREAD

**Issue by toniosj** [BenoitBounar/Pack-Conf-eXoDOS6.0r2-for-DosBOX-Pure-RECALBOX#4]
Missing .conf files for these games:

- Games People Play, The - Gin, Cribbage, Checkers, and Backgammon (1990).zip
- Whale's Voyage II (1995).zip
- Where in the World is Carmen Sandiego CD (1995).zip
- Wing Commander II Deluxe Edition (1992).zip

**Comment by BenoitBounar** [comment]
Fixed :
Commit 20ddef5
